# 这一页的内容可以修改值，但是不要删除行。初次使用主题请务必阅读官方文档！！！
# 这一页的内容可以修改值，但是不要删除行。初次使用主题请务必阅读官方文档！！！
# 这一页的内容可以修改值，但是不要删除行。初次使用主题请务必阅读官方文档！！！


############################### 基本信息 ###############################
# info:
#   name: Material X
#   docs: https://xaoxuu.com/wiki/material-x/
#   # 主题的CDN地址。如需启用CDN，请在主目录的config中设置，详见文档。
#   cdn: https://cdn.jsdelivr.net/gh/xaoxuu/cdn-material-x@19.2.21/


############################### 主题样式 ###############################
# style: material    # material: 导航栏和标题栏背景是主题色
style: pure        # pure: 导航栏和标题栏背景是白色


############################### 服务开关 ###############################
# 服务开关，如果你想禁用某些功能，直接设置为false或者注释掉，相关的js脚本就不会加载。
# 有些服务这里打开了也未必会生效，还需要额外的配置，详见文档。
services:
  cdn: false
  scrollreveal: true
  nodewaves: true
  busuanzi: true
  fastclick: true
  # leancloud_visitors: true
  # recommended_posts: true   # 需要安装插件  hexo-recommended-posts
  popular_posts: true   # 需要安装插件  hexo-related-popular-posts
  comments: true
  volantis: true
  music: false
  share: true
  qrcode: true    # 需要安装插件  npm i -S hexo-helper-qrcode


# 友链页头像占位图
# loading_img: https://cdn.jsdelivr.net/gh/xaoxuu/volantis@1.0/img/qq/亲亲.gif

# 推荐文章
recommended_posts:
  autoDisplay: false # 自动在文章底部显示推荐文章，如果你使用Material-X主题，这里要设置为false。
  server: https://api.truelaurel.com # 后端推荐服务器地址
  timeoutInMillis: 10000 # 服务时长，超过此时长，则使用离线推荐模式
  excludePattern: []
  titleHtml: <h4>推荐文章</h4> #自定义标题
  internalLinks: 3 # 内部文章数量
  externalLinks: 2 # 外部文章数量
  fixedNumber: false


# Search
search:
  enable: true
  service: hexo
  # google
  google_api_key:
  google_engine_id:
  # algolia
  algolia_app_id:
  algolia_api_key:
  algolia_index_name:
  # azure
  azure_service_name:
  azure_index_name:
  azure_query_key:
  # baidu
  baidu_api_id:

# Less
less:
  compress: true

# nav_menu:
#   - name: home
#     icon: fas fa-home
#     url: https://xaoxuu.com/
#   - name: blogs
#     icon: fas fa-rss
#     url: /
#   - name: archives
#     icon: fas fa-archive
#     url: archives/
#   - name: friends
#     icon: fas fa-users
#     url: friends/
